swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      description: "returns all TODOs avaialble in ElasticSearch (or) DB."
      operationId: "GetAllTodos"
      parameters: []
      responses:
        200:
          description: "An array of TODOs is returned"
          schema:
            type: "array"
            items: 
              $ref: "#/definitions/Todo"
      x-swagger-router-controller: "GetAllTodos"
    post:
      description: "creates a new TODO"
      operationId: "CreateTodo"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "todo"
        description: "the TODO to be created"
        required: true
        schema: 
          $ref: "#/definitions/Todo"
      responses:
          200: 
            description: "Successfully created a new TODO"
      x-swagger-router-controller: "CreateTodo"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Todo:
    type: "object"
    properties:
      todoId:
        type: "integer"
        description: "Primary key, unique identifier for TODOs"
      todoTitle:
        type: "string"
        description: "the name of a TODO"
      dateCreated:
        type: "string"
        format: "date-time"
        description: "Timestamp of when the TODO was created. Created by the server"
      author:
        type: "string"
        description: "user who created the TODO"
      dueDate:
        type: "string"
        format: "date-time"
        description: "date the TODO must be completed by"
      completed:
        type: "boolean"
        description: "whether the todo has been completed or not"
        
        